# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 112) do

  create_table "account_receivables", :force => true do |t|
  end

  create_table "addresses", :force => true do |t|
    t.column "post_office_box",  :string,  :limit => 50
    t.column "extended_address", :string,  :limit => 50
    t.column "street_address",   :string,  :limit => 50
    t.column "locality",         :string,  :limit => 50
    t.column "region",           :string,  :limit => 50
    t.column "postal_code",      :string,  :limit => 50
    t.column "country_name",     :string,  :limit => 50
    t.column "type",             :string
    t.column "vcard_id",         :integer
    t.column "address_type",     :string
  end

  add_index "addresses", ["vcard_id"], :name => "addresses_vcard_id_index"

  create_table "bills", :force => true do |t|
    t.column "case_id",                     :integer
    t.column "amount",                      :float
    t.column "created_at",                  :datetime
    t.column "updated_at",                  :datetime
    t.column "is_storno",                   :boolean
    t.column "praxistar_rechnungs_id",      :integer
    t.column "praxistar_leistungsblatt_id", :integer
  end

  add_index "bills", ["case_id"], :name => "index_bills_on_case_id"
  add_index "bills", ["praxistar_rechnungs_id"], :name => "index_bills_on_praxistar_rechnungs_id"
  add_index "bills", ["praxistar_leistungsblatt_id"], :name => "index_bills_on_praxistar_leistungsblatt_id"

  create_table "cases", :force => true do |t|
    t.column "examination_method_id",       :integer
    t.column "examination_date",            :date
    t.column "classification_id",           :integer
    t.column "praxistar_eingangsnr",        :string,   :limit => 8
    t.column "patient_id",                  :integer
    t.column "doctor_id",                   :integer
    t.column "entry_date",                  :date
    t.column "screener_id",                 :integer,  :limit => 255
    t.column "insurance_id",                :integer
    t.column "insurance_nr",                :string
    t.column "praxistar_leistungsblatt_id", :integer
    t.column "screened_at",                 :datetime
    t.column "result_report_printed_at",    :datetime
    t.column "needs_p16",                   :boolean,                 :default => false
    t.column "finding_text",                :text
    t.column "remarks",                     :text
    t.column "assigned_at",                 :datetime
    t.column "assigned_screener_id",        :datetime
    t.column "intra_day_id",                :integer
    t.column "hpv_p16_prepared_at",         :datetime
    t.column "hpv_p16_prepared_by",         :integer
    t.column "scheduled_at",                :datetime
    t.column "scheduled_for",               :integer
    t.column "centrifuged_at",              :datetime
    t.column "centrifuged_by",              :integer
    t.column "needs_hpv",                   :boolean,                 :default => false
    t.column "needs_review",                :boolean,                 :default => false
    t.column "first_entry_by",              :integer
    t.column "first_entry_at",              :datetime
    t.column "review_by",                   :integer
    t.column "review_at",                   :datetime
    t.column "p16_notice_printed_at",       :datetime
    t.column "email_sent_at",               :datetime
  end

  add_index "cases", ["praxistar_eingangsnr"], :name => "cases_praxistar_eingangsnr_index", :unique => true
  add_index "cases", ["patient_id"], :name => "cases_patient_id_index"
  add_index "cases", ["doctor_id"], :name => "cases_doctor_id_index"
  add_index "cases", ["insurance_id"], :name => "cases_insurance_id_index"
  add_index "cases", ["result_report_printed_at"], :name => "i1"

  create_table "cases_finding_classes", :id => false, :force => true do |t|
    t.column "case_id",          :integer
    t.column "finding_class_id", :integer
    t.column "position",         :integer
  end

  add_index "cases_finding_classes", ["case_id", "finding_class_id"], :name => "cases_finding_classes_case_id_index", :unique => true

  create_table "cases_finding_classes_second", :id => false, :force => true do |t|
    t.column "case_id",          :integer
    t.column "finding_class_id", :integer
  end

  create_table "cases_mailings", :id => false, :force => true do |t|
    t.column "case_id",    :integer
    t.column "mailing_id", :integer
  end

  add_index "cases_mailings", ["case_id"], :name => "index_cases_mailings_on_case_id"
  add_index "cases_mailings", ["mailing_id"], :name => "index_cases_mailings_on_mailing_id"

  create_table "cases_second", :force => true do |t|
    t.column "examination_method_id", :integer
    t.column "examination_date",      :date
    t.column "classification_id",     :integer
    t.column "praxistar_eingangsnr",  :string,  :limit => 8
  end

  create_table "classification_groups", :force => true do |t|
    t.column "title",    :string
    t.column "position", :integer
  end

  create_table "classification_tarmed_leistungens", :force => true do |t|
    t.column "classification_id",  :integer
    t.column "tarmed_leistung_id", :string
    t.column "position",           :integer
    t.column "parent_id",          :string
  end

  create_table "classifications", :force => true do |t|
    t.column "name",                    :text
    t.column "code",                    :string,  :limit => 10
    t.column "examination_method_id",   :integer
    t.column "classification_group_id", :integer
  end

  create_table "delievery_returns", :force => true do |t|
    t.column "case_id",             :integer
    t.column "fax_sent_at",         :datetime
    t.column "bill_id",             :integer
    t.column "closed_at",           :datetime
    t.column "address_verified_at", :datetime
  end

  create_table "doctors", :force => true do |t|
    t.column "code",              :string
    t.column "speciality",        :string
    t.column "praxis_vcard",      :integer
    t.column "private_vcard",     :integer
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
    t.column "active",            :boolean,  :default => true
    t.column "billing_doctor_id", :integer
    t.column "login",             :string
    t.column "password",          :string,   :default => "",   :null => false
  end

  add_index "doctors", ["praxis_vcard"], :name => "doctors_praxis_vcard_index"
  add_index "doctors", ["private_vcard"], :name => "doctors_private_vcard_index"

  create_table "doctors_offices", :id => false, :force => true do |t|
    t.column "office_id", :integer
    t.column "doctor_id", :integer
  end

  create_table "employees", :force => true do |t|
    t.column "work_vcard_id",    :integer
    t.column "private_vcard_id", :integer
    t.column "code",             :string
    t.column "born_on",          :date
    t.column "workload",         :float
  end

  create_table "examination_methods", :force => true do |t|
    t.column "name", :string
  end

  create_table "exports", :force => true do |t|
    t.column "started_at",   :datetime
    t.column "finished_at",  :datetime
    t.column "update_count", :integer,  :default => 0
    t.column "create_count", :integer,  :default => 0
    t.column "error_count",  :integer,  :default => 0
    t.column "error_ids",    :string,   :default => ""
    t.column "model",        :string
    t.column "find_params",  :string
    t.column "pid",          :integer
    t.column "record_count", :integer
  end

  create_table "finding_classes", :force => true do |t|
    t.column "name", :text
    t.column "code", :text
  end

  create_table "finding_classes_finding_groups", :id => false, :force => true do |t|
    t.column "finding_class_id", :integer
    t.column "finding_group_id", :integer
  end

  create_table "finding_classes_second", :force => true do |t|
    t.column "name", :text
    t.column "code", :text
  end

  create_table "finding_groups", :force => true do |t|
    t.column "name", :string
  end

  create_table "honorific_prefixes", :force => true do |t|
    t.column "sex",  :integer
    t.column "name", :string
  end

  create_table "imports", :force => true do |t|
    t.column "started_at",   :datetime
    t.column "finished_at",  :datetime
    t.column "update_count", :integer,  :default => 0
    t.column "create_count", :integer,  :default => 0
    t.column "error_count",  :integer,  :default => 0
    t.column "error_ids",    :string,   :default => ""
    t.column "model",        :string
    t.column "find_params",  :string
    t.column "pid",          :integer
    t.column "record_count", :integer
  end

  create_table "insurances", :force => true do |t|
    t.column "vcard_id",   :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "mailings", :force => true do |t|
    t.column "created_at",         :datetime
    t.column "doctor_id",          :integer
    t.column "printed_at",         :datetime
    t.column "email_delivered_at", :datetime
  end

  add_index "mailings", ["doctor_id"], :name => "index_mailings_on_doctor_id"
  add_index "mailings", ["created_at"], :name => "i1"

  create_table "offices", :force => true do |t|
    t.column "name",     :string
    t.column "login",    :string
    t.column "password", :string
  end

  create_table "order_forms", :force => true do |t|
    t.column "file",       :text
    t.column "created_at", :datetime
    t.column "case_id",    :integer
  end

  add_index "order_forms", ["case_id"], :name => "index_order_forms_on_case_id"

  create_table "pages", :force => true do |t|
    t.column "position", :integer
    t.column "scan_id",  :integer
    t.column "file",     :string
  end

  create_table "patients", :force => true do |t|
    t.column "vcard_id",            :integer
    t.column "birth_date",          :date
    t.column "insurance_id",        :integer
    t.column "insurance_nr",        :string
    t.column "sex",                 :integer
    t.column "only_year_of_birth",  :integer
    t.column "doctor_id",           :integer
    t.column "billing_vcard_id",    :integer
    t.column "remarks",             :text
    t.column "created_at",          :datetime
    t.column "updated_at",          :datetime
    t.column "dunning_stop",        :boolean,  :default => false
    t.column "use_billing_address", :boolean,  :default => false
    t.column "deceased",            :boolean,  :default => false
    t.column "doctor_patient_nr",   :string
  end

  add_index "patients", ["updated_at"], :name => "patients_updated_at_index"
  add_index "patients", ["vcard_id"], :name => "patients_vcard_id_index"
  add_index "patients", ["billing_vcard_id"], :name => "patients_billing_vcard_id_index"
  add_index "patients", ["doctor_id"], :name => "patients_doctor_id_index"
  add_index "patients", ["insurance_id"], :name => "patients_insurance_id_index"

  create_table "payments", :force => true do |t|
  end

  create_table "phone_numbers", :force => true do |t|
    t.column "number",            :string,  :limit => 50
    t.column "phone_number_type", :string,  :limit => 50
    t.column "vcard_id",          :integer
  end

  add_index "phone_numbers", ["vcard_id"], :name => "phone_numbers_vcard_id_index"

  create_table "praxistar_bill_journals", :force => true do |t|
  end

  create_table "scans", :force => true do |t|
    t.column "created_at", :datetime
  end

  create_table "schema_migrations", :id => false, :force => true do |t|
    t.column "version", :string, :default => "", :null => false
  end

  add_index "schema_migrations", ["version"], :name => "unique_schema_migrations", :unique => true

  create_table "shop_orders", :force => true do |t|
  end

  create_table "tasks", :force => true do |t|
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "due_on",      :datetime
    t.column "amount",      :integer
    t.column "employee_id", :integer
    t.column "type",        :text
  end

  create_table "top_finding_classes", :force => true do |t|
    t.column "classification_id", :integer
    t.column "finding_class_id",  :integer
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string,   :limit => 40
    t.column "name",                      :string,   :limit => 100, :default => ""
    t.column "email",                     :string,   :limit => 100
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string,   :limit => 40
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
    t.column "state",                     :string,                  :default => "passive"
    t.column "deleted_at",                :datetime
    t.column "object_id",                 :integer
    t.column "object_type",               :string
    t.column "wants_email",               :boolean,                 :default => false
    t.column "wants_prints",              :boolean,                 :default => true
  end

  add_index "users", ["login"], :name => "index_users_on_login", :unique => true

  create_table "vcards", :force => true do |t|
    t.column "full_name",          :string,  :limit => 50
    t.column "nickname",           :string,  :limit => 50
    t.column "address",            :integer
    t.column "billing_address_id", :integer
    t.column "address_id",         :integer
    t.column "family_name",        :string,  :limit => 50
    t.column "given_name",         :string,  :limit => 50
    t.column "additional_name",    :string,  :limit => 50
    t.column "honorific_prefix",   :string,  :limit => 50
    t.column "honorific_suffix",   :string,  :limit => 50
  end

end
