# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "addresses", :force => true do |t|
    t.column "post_office_box", :string, :limit => 50
    t.column "extended_address", :string, :limit => 50
    t.column "street_address", :string, :limit => 50
    t.column "locality", :string, :limit => 50
    t.column "region", :string, :limit => 50
    t.column "postal_code", :string, :limit => 50
    t.column "country_name", :string, :limit => 50
    t.column "type", :string
    t.column "vcard_id", :integer
    t.column "address_type", :string
  end

  create_table "insurances", :force => true do |t|
    t.column "vcard_id", :integer
  end

  create_table "vcards", :force => true do |t|
    t.column "full_name", :string, :limit => 50
    t.column "nickname", :string, :limit => 50
    t.column "address", :integer
    t.column "billing_address_id", :integer
    t.column "address_id", :integer
    t.column "family_name", :string, :limit => 50
    t.column "given_name", :string, :limit => 50
    t.column "additional_name", :string, :limit => 50
    t.column "honorific_prefix", :string, :limit => 50
    t.column "honorific_suffix", :string, :limit => 50
  end

end
